<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nguoidung [
    <!ELEMENT nguoidung (tendangnhap, email, matkhau, ngay_tao, danhsachphat+)>
    <!ATTLIST nguoidung nguoidung_id ID #REQUIRED>

    <!ELEMENT tendangnhap (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT matkhau (#PCDATA)>
    <!ELEMENT ngay_tao (#PCDATA)>

    <!ELEMENT danhsachphat (ten_danh_sach, ngay_tao, danhsach_baihat+)>
    <!ATTLIST danhsachphat danhsach_id ID #REQUIRED>

    <!ELEMENT ten_danh_sach (#PCDATA)>
    <!ELEMENT danhsach_baihat (baihat)>
    <!ATTLIST danhsach_baihat ds_bai_hat ID #REQUIRED
                               thu_tu CDATA #IMPLIED
                               ngay_them CDATA #IMPLIED>

    <!ELEMENT baihat (tieu_de, thoi_luong, ngay_phat_hanh, duong_dan_file, album, nghesi, theloai)>
    <!ATTLIST baihat baihat_id ID #REQUIRED>

    <!ELEMENT tieu_de (#PCDATA)>
    <!ELEMENT thoi_luong (#PCDATA)>
    <!ELEMENT ngay_phat_hanh (#PCDATA)>
    <!ELEMENT duong_dan_file (#PCDATA)>

    <!ELEMENT album (ten_album, ngay_phat_hanh, anh_bia)>
    <!ATTLIST album album_id ID #REQUIRED>

    <!ELEMENT ten_album (#PCDATA)>
    <!ELEMENT anh_bia (#PCDATA)>

    <!ELEMENT nghesi (ten_nghesi, tieu_su, quoc_gia)>
    <!ATTLIST nghesi nghesi_id ID #REQUIRED>

    <!ELEMENT ten_nghesi (#PCDATA)>
    <!ELEMENT tieu_su (#PCDATA)>
    <!ELEMENT quoc_gia (#PCDATA)>

    <!ELEMENT theloai (ten_theloai, mo_ta)>
    <!ATTLIST theloai theloai_id ID #REQUIRED>

    <!ELEMENT ten_theloai (#PCDATA)>
    <!ELEMENT mo_ta (#PCDATA)>
]>
<nguoidung nguoidung_id="u1">
    <tendangnhap>minhhoa</tendangnhap>
    <email>minhhoa@example.com</email>
    <matkhau>123456</matkhau>
    <ngay_tao>2025-10-05</ngay_tao>

    <danhsachphat danhsach_id="pl1">
        <ten_danh_sach>Nhạc yêu thích</ten_danh_sach>
        <ngay_tao>2025-10-05</ngay_tao>
        
        <danhsach_baihat ds_bai_hat="dbh1" thu_tu="1" ngay_them="2025-10-05">
            <baihat baihat_id="bh101">
                <tieu_de>Chạm khẽ tim anh một chút thôi</tieu_de>
                <thoi_luong>240</thoi_luong>
                <ngay_phat_hanh>2024-12-20</ngay_phat_hanh>
                <duong_dan_file>music/chamkhetimanh.mp3</duong_dan_file>
                
                <album album_id="al10">
                    <ten_album>Ballad Việt</ten_album>
                    <ngay_phat_hanh>2024-12-15</ngay_phat_hanh>
                    <anh_bia>images/balladviet.jpg</anh_bia>
                </album>

                <nghesi nghesi_id="ng50">
                    <ten_nghesi>Noo Phước Thịnh</ten_nghesi>
                    <tieu_su>Ca sĩ nhạc trẻ Việt Nam</tieu_su>
                    <quoc_gia>Việt Nam</quoc_gia>
                </nghesi>

                <theloai theloai_id="tl5">
                    <ten_theloai>Pop Ballad</ten_theloai>
                    <mo_ta>Nhạc nhẹ, dễ nghe</mo_ta>
                </theloai>
            </baihat>
        </danhsach_baihat>
    </danhsachphat>
</nguoidung>
